include: "rules/common.smk"
include: "rules/fastq_screen.smk"
include: "rules/fastqc.smk"
include: "rules/multiqc.smk"
include: "rules/prepare_input.smk"


rule fair_fastqc_multiqc_target:
    input:
        multiqc=[
            "results/QC/MultiQC_FastQC.html",
            "results/QC/MultiQC_FastQC_data.zip",
        ],
    output:
        touch("tmp/targets/fair_fastqc_multiqc_target.flag"),
    localrule: True
    threads: 1
    resources:
        mem_mb=128,
        runtime=2,
        tmpdir="tmp",
    log:
        "logs/fair_fastqc_multiqc_target.log",
    benchmark:
        "benchmark/fair_fastqc_multiqc_target.tsv"
