# Path to file describing samples and their file-paths
samples: config/samples.csv

# Optional parameters
params:
    fastq_screen:
      # Path to configuration file
      fastq_screen_config: "/mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/fastq_screen.conf"

# Optional path to a file describing genomes
genomes: config/genomes.csv
