# Path to file describing samples and their file-paths
samples: config/samples.csv

# Optional parameters
# params:
  # Path to configuration file
  # fair_fastqc_multiqc_fastq_screen_config: "/mnt/beegfs02/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/fastq_screen.conf"

# Optional path to a file describing genomes
genomes: config/genomes.csv
