$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

samples:
  type: string
  description: Path to the CSV file defining samples and their corresponding fastq paths


params:
  type: object
  description: Optional parameters for FastQC and MultiQC
  fastqc:
    type: string
    description: Optional parameters for FastQC
  multiqc:
    type: string
    description: Optional parameters for MultiQC

required:
  - samples