$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

samples:
  type: string
  description: Path to the CSV file defining samples and their corresponding fastq paths


params:
  type: object
  description: Parameters for each (sub) pipelines
  fair_fastqc_multiqc:
    type: object
    description: Optional parameters for FastQC, MultiQC, FastQScreen, and NGSDerive
    fastqc:
      type: string
      description: Optional parameters for FastQC
    multiqc:
      type: string
      description: Optional parameters for MultiQC
    fastq_screen:
      type: object
      subset:
        type: integer
        description: Number of reads used to build statistics
      fastq_screen_config:
        type: string
        description: Path to fastq screen configuration
      aligner:
        type: string
        description: Aligner used to index references
        pattern: "^bowtie2?"
    ngsderive:
      type: object
      description: backward analyse your fastq
      instrument:
        type: string
        description: estimate sequencing instrument
      encoding:
        type: string
        description: estimate read encoding
      readlen:
        type: string
        description: estimate original readlen
