$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

samples:
  type: string
  description: Path to the CSV file defining samples and their corresponding fastq paths


params:
  type: object
  description: Parameters for each (sub) pipelines

  fair_rnaseq_salmon_quant_multiqc_config:
    type: object
    description: Mapping object of all MultiQC sub-caregories

  fair_fastqc_multiqc_fastq_screen:
    type: object
    description: Optional parameters for FastQ Screen
    subset:
      type: integer
      description: Number of reads used to assign genomes

    aligner:
      type: str
      description: Aligner used by FastQ Screen
      pattern: "^bowtie2?"

    config:
      type: str
      description: Path to configuration file

  fair_fastqc_multiqc_fastqc:
    type: str
    description: Optional parameters for fastqc

  fair_fastqc_multiqc_multiqc:
    type: str
    description: Optional parameters for multiqc
 
